/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ContractDTO {
    /**
    * [Cid](https://github.com/multiformats/cid) (version 1) - special content identifier. 
    */
    'drive'?: string;
    /**
    * Hex encoded public key.
    */
    'owner'?: string;
    /**
    * Hex encoded public keys.
    */
    'replicators'?: Array<string>;
    'root'?: string;
    /**
    * Block height when the Contract was started.
    */
    'created'?: number;
    'duration'?: number;
    'space'?: number;
    'replicas'?: number;
    'percentApprovers'?: number;
    'billingPrice'?: number;
    'billingPeriod'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "drive",
            "baseName": "drive",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        },
        {
            "name": "replicators",
            "baseName": "replicators",
            "type": "Array<string>"
        },
        {
            "name": "root",
            "baseName": "root",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number"
        },
        {
            "name": "space",
            "baseName": "space",
            "type": "number"
        },
        {
            "name": "replicas",
            "baseName": "replicas",
            "type": "number"
        },
        {
            "name": "percentApprovers",
            "baseName": "percentApprovers",
            "type": "number"
        },
        {
            "name": "billingPrice",
            "baseName": "billingPrice",
            "type": "number"
        },
        {
            "name": "billingPeriod",
            "baseName": "billingPeriod",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ContractDTO.attributeTypeMap;
    }
}

