/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons.  
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class Error {
    /**
    * Error message
    */
    'message'?: string;
    /**
    * * 0 - Normal - is a normal error. The command failed for some reason that\'s not a bug. * 1 - Client - means the client made an invalid request. * 2 - Implementation - means there\'s a bug in the implementation. * 3 - RateLimited - is returned when the operation has been rate-limited. * 4 - Forbidden - is returned when the client doesn\'t have permission to       perform the requested operation. 
    */
    'code'?: Error.CodeEnum;
    'type'?: Error.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "Error.CodeEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Error.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return Error.attributeTypeMap;
    }
}

export namespace Error {
    export enum CodeEnum {
        NUMBER_0 = <any> 0,
        NUMBER_1 = <any> 1,
        NUMBER_2 = <any> 2
    }
    export enum TypeEnum {
        Error = <any> 'error'
    }
}
