/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons.  
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* File statistics
*/
export class Stat {
    'name'?: string;
    'size'?: number;
    'type'?: Stat.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Stat.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return Stat.attributeTypeMap;
    }
}

export namespace Stat {
    export enum TypeEnum {
        File = <any> 'file',
        Dir = <any> 'dir'
    }
}
