/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddrListWrap
 */
export interface AddrListWrap {
    /**
     * 
     * @type {Array<string>}
     * @memberof AddrListWrap
     */
    addrs?: Array<string>;
}

export function AddrListWrapFromJSON(json: any): AddrListWrap {
    return AddrListWrapFromJSONTyped(json, false);
}

export function AddrListWrapFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddrListWrap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addrs': !exists(json, 'Addrs') ? undefined : json['Addrs'],
    };
}

export function AddrListWrapToJSON(value?: AddrListWrap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Addrs': value.addrs,
    };
}


