/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Wrapper for array of Cids
 * @export
 * @interface CidListWrap
 */
export interface CidListWrap {
    /**
     * 
     * @type {Array<string>}
     * @memberof CidListWrap
     */
    ids?: Array<string>;
}

export function CidListWrapFromJSON(json: any): CidListWrap {
    return CidListWrapFromJSONTyped(json, false);
}

export function CidListWrapFromJSONTyped(json: any, ignoreDiscriminator: boolean): CidListWrap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ids': !exists(json, 'Ids') ? undefined : json['Ids'],
    };
}

export function CidListWrapToJSON(value?: CidListWrap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Ids': value.ids,
    };
}


