/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CidResultWrap
 */
export interface CidResultWrap {
    /**
     * [Cid](https://github.com/multiformats/cid) (version 1) - special content identifier.
     * @type {string}
     * @memberof CidResultWrap
     */
    result?: string;
}

export function CidResultWrapFromJSON(json: any): CidResultWrap {
    return CidResultWrapFromJSONTyped(json, false);
}

export function CidResultWrapFromJSONTyped(json: any, ignoreDiscriminator: boolean): CidResultWrap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'Result') ? undefined : json['Result'],
    };
}

export function CidResultWrapToJSON(value?: CidResultWrap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Result': value.result,
    };
}


