/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CidWithPath
 */
export interface CidWithPath {
    /**
     * [Cid](https://github.com/multiformats/cid) (version 1) - special content identifier.
     * @type {string}
     * @memberof CidWithPath
     */
    u?: string;
}

export function CidWithPathFromJSON(json: any): CidWithPath {
    return CidWithPathFromJSONTyped(json, false);
}

export function CidWithPathFromJSONTyped(json: any, ignoreDiscriminator: boolean): CidWithPath {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'u': !exists(json, '/') ? undefined : json['/'],
    };
}

export function CidWithPathToJSON(value?: CidWithPath | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '/': value.u,
    };
}


