/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Drive contract
 * @export
 * @interface Contract
 */
export interface Contract {
    /**
     * [Cid](https://github.com/multiformats/cid) (version 1) - special content identifier.
     * @type {string}
     * @memberof Contract
     */
    drive?: string;
    /**
     * Hex encoded public key.
     * @type {string}
     * @memberof Contract
     */
    owner?: string;
    /**
     * Hex encoded public keys.
     * @type {Array<string>}
     * @memberof Contract
     */
    replicators?: Array<string>;
    /**
     * [Cid](https://github.com/multiformats/cid) (version 1) - special content identifier.
     * @type {string}
     * @memberof Contract
     */
    root?: string;
    /**
     * Block height when the Contract was started.
     * @type {number}
     * @memberof Contract
     */
    created?: number;
    /**
     * 
     * @type {number}
     * @memberof Contract
     */
    duration?: number;
    /**
     * 
     * @type {number}
     * @memberof Contract
     */
    space?: number;
    /**
     * 
     * @type {number}
     * @memberof Contract
     */
    replicas?: number;
    /**
     * 
     * @type {number}
     * @memberof Contract
     */
    minReplicators?: number;
    /**
     * 
     * @type {number}
     * @memberof Contract
     */
    percentApprovers?: number;
    /**
     * 
     * @type {number}
     * @memberof Contract
     */
    billingPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof Contract
     */
    billingPeriod?: number;
}

export function ContractFromJSON(json: any): Contract {
    return ContractFromJSONTyped(json, false);
}

export function ContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): Contract {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'drive': !exists(json, 'drive') ? undefined : json['drive'],
        'owner': !exists(json, 'owner') ? undefined : json['owner'],
        'replicators': !exists(json, 'replicators') ? undefined : json['replicators'],
        'root': !exists(json, 'root') ? undefined : json['root'],
        'created': !exists(json, 'created') ? undefined : json['created'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'space': !exists(json, 'space') ? undefined : json['space'],
        'replicas': !exists(json, 'replicas') ? undefined : json['replicas'],
        'minReplicators': !exists(json, 'minReplicators') ? undefined : json['minReplicators'],
        'percentApprovers': !exists(json, 'percentApprovers') ? undefined : json['percentApprovers'],
        'billingPrice': !exists(json, 'billingPrice') ? undefined : json['billingPrice'],
        'billingPeriod': !exists(json, 'billingPeriod') ? undefined : json['billingPeriod'],
    };
}

export function ContractToJSON(value?: Contract | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'drive': value.drive,
        'owner': value.owner,
        'replicators': value.replicators,
        'root': value.root,
        'created': value.created,
        'duration': value.duration,
        'space': value.space,
        'replicas': value.replicas,
        'minReplicators': value.minReplicators,
        'percentApprovers': value.percentApprovers,
        'billingPrice': value.billingPrice,
        'billingPeriod': value.billingPeriod,
    };
}


