/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Contract,
    ContractFromJSON,
    ContractFromJSONTyped,
    ContractToJSON,
} from './';

/**
 * Wrapper for single drive contract
 * @export
 * @interface ContractWrap
 */
export interface ContractWrap {
    /**
     * 
     * @type {Contract}
     * @memberof ContractWrap
     */
    contract?: Contract;
}

export function ContractWrapFromJSON(json: any): ContractWrap {
    return ContractWrapFromJSONTyped(json, false);
}

export function ContractWrapFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractWrap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contract': !exists(json, 'Contract') ? undefined : ContractFromJSON(json['Contract']),
    };
}

export function ContractWrapToJSON(value?: ContractWrap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Contract': ContractToJSON(value.contract),
    };
}


