/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CidWithPath,
    CidWithPathFromJSON,
    CidWithPathFromJSONTyped,
    CidWithPathToJSON,
} from './';

/**
 * Wrapper for array of Cids
 * @export
 * @interface ExecutionsWrap
 */
export interface ExecutionsWrap {
    /**
     * 
     * @type {Array<CidWithPath>}
     * @memberof ExecutionsWrap
     */
    ids?: Array<CidWithPath>;
}

export function ExecutionsWrapFromJSON(json: any): ExecutionsWrap {
    return ExecutionsWrapFromJSONTyped(json, false);
}

export function ExecutionsWrapFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutionsWrap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ids': !exists(json, 'Ids') ? undefined : ((json['Ids'] as Array<any>).map(CidWithPathFromJSON)),
    };
}

export function ExecutionsWrapToJSON(value?: ExecutionsWrap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Ids': value.ids === undefined ? undefined : ((value.ids as Array<any>).map(CidWithPathToJSON)),
    };
}


