/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteDTO
 */
export interface InviteDTO {
    /**
     * [Cid](https://github.com/multiformats/cid) (version 1) - special content identifier.
     * @type {string}
     * @memberof InviteDTO
     */
    drive?: string;
    /**
     * Hex encoded public key.
     * @type {string}
     * @memberof InviteDTO
     */
    owner?: string;
    /**
     * 
     * @type {number}
     * @memberof InviteDTO
     */
    duration?: number;
    /**
     * 
     * @type {number}
     * @memberof InviteDTO
     */
    space?: number;
    /**
     * 
     * @type {number}
     * @memberof InviteDTO
     */
    billingPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof InviteDTO
     */
    billingPeriod?: number;
    /**
     * 
     * @type {number}
     * @memberof InviteDTO
     */
    replicas?: number;
    /**
     * 
     * @type {number}
     * @memberof InviteDTO
     */
    minReplicators?: number;
    /**
     * 
     * @type {number}
     * @memberof InviteDTO
     */
    percentApprovers?: number;
}

export function InviteDTOFromJSON(json: any): InviteDTO {
    return InviteDTOFromJSONTyped(json, false);
}

export function InviteDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'drive': !exists(json, 'drive') ? undefined : json['drive'],
        'owner': !exists(json, 'owner') ? undefined : json['owner'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'space': !exists(json, 'space') ? undefined : json['space'],
        'billingPrice': !exists(json, 'billingPrice') ? undefined : json['billingPrice'],
        'billingPeriod': !exists(json, 'billingPeriod') ? undefined : json['billingPeriod'],
        'replicas': !exists(json, 'replicas') ? undefined : json['replicas'],
        'minReplicators': !exists(json, 'minReplicators') ? undefined : json['minReplicators'],
        'percentApprovers': !exists(json, 'percentApprovers') ? undefined : json['percentApprovers'],
    };
}

export function InviteDTOToJSON(value?: InviteDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'drive': value.drive,
        'owner': value.owner,
        'duration': value.duration,
        'space': value.space,
        'billingPrice': value.billingPrice,
        'billingPeriod': value.billingPeriod,
        'replicas': value.replicas,
        'minReplicators': value.minReplicators,
        'percentApprovers': value.percentApprovers,
    };
}


