/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PeerIdWrap
 */
export interface PeerIdWrap {
    /**
     * network ID of a node
     * @type {string}
     * @memberof PeerIdWrap
     */
    iD?: string;
}

export function PeerIdWrapFromJSON(json: any): PeerIdWrap {
    return PeerIdWrapFromJSONTyped(json, false);
}

export function PeerIdWrapFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeerIdWrap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iD': !exists(json, 'ID') ? undefined : json['ID'],
    };
}

export function PeerIdWrapToJSON(value?: PeerIdWrap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ID': value.iD,
    };
}


