/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Peer
 */
export interface Peer {
    /**
     * 
     * @type {Array<string>}
     * @memberof Peer
     */
    addrs?: Array<string>;
    /**
     * network ID of a node
     * @type {string}
     * @memberof Peer
     */
    iD?: string;
}

export function PeerFromJSON(json: any): Peer {
    return PeerFromJSONTyped(json, false);
}

export function PeerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Peer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addrs': !exists(json, 'Addrs') ? undefined : json['Addrs'],
        'iD': !exists(json, 'ID') ? undefined : json['ID'],
    };
}

export function PeerToJSON(value?: Peer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Addrs': value.addrs,
        'ID': value.iD,
    };
}


