/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResultsWrap
 */
export interface ResultsWrap {
    /**
     * 
     * @type {Array<string>}
     * @memberof ResultsWrap
     */
    results?: Array<string>;
}

export function ResultsWrapFromJSON(json: any): ResultsWrap {
    return ResultsWrapFromJSONTyped(json, false);
}

export function ResultsWrapFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultsWrap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'Results') ? undefined : json['Results'],
    };
}

export function ResultsWrapToJSON(value?: ResultsWrap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Results': value.results,
    };
}


