/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CidWithPath,
    CidWithPathFromJSON,
    CidWithPathFromJSONTyped,
    CidWithPathToJSON,
} from './';

/**
 * File statistics
 * @export
 * @interface Stat
 */
export interface Stat {
    /**
     * 
     * @type {string}
     * @memberof Stat
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Stat
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof Stat
     */
    type?: StatTypeEnum;
    /**
     * 
     * @type {CidWithPath}
     * @memberof Stat
     */
    cid?: CidWithPath;
}

export function StatFromJSON(json: any): Stat {
    return StatFromJSONTyped(json, false);
}

export function StatFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'size': !exists(json, 'Size') ? undefined : json['Size'],
        'type': !exists(json, 'Type') ? undefined : json['Type'],
        'cid': !exists(json, 'Cid') ? undefined : CidWithPathFromJSON(json['Cid']),
    };
}

export function StatToJSON(value?: Stat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'Size': value.size,
        'Type': value.type,
        'Cid': CidWithPathToJSON(value.cid),
    };
}

/**
* @export
* @enum {string}
*/
export enum StatTypeEnum {
    File = 'file',
    Dir = 'dir'
}


