/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Stat,
    StatFromJSON,
    StatFromJSONTyped,
    StatToJSON,
} from './';

/**
 * 
 * @export
 * @interface StatWrap
 */
export interface StatWrap {
    /**
     * 
     * @type {Stat}
     * @memberof StatWrap
     */
    stat?: Stat;
}

export function StatWrapFromJSON(json: any): StatWrap {
    return StatWrapFromJSONTyped(json, false);
}

export function StatWrapFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatWrap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stat': !exists(json, 'Stat') ? undefined : StatFromJSON(json['Stat']),
    };
}

export function StatWrapToJSON(value?: StatWrap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Stat': StatToJSON(value.stat),
    };
}


