/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Stat,
    StatFromJSON,
    StatFromJSONTyped,
    StatToJSON,
} from './';

/**
 * 
 * @export
 * @interface StatListWrap
 */
export interface StatListWrap {
    /**
     * 
     * @type {Array<Stat>}
     * @memberof StatListWrap
     */
    list?: Array<Stat>;
}

export function StatListWrapFromJSON(json: any): StatListWrap {
    return StatListWrapFromJSONTyped(json, false);
}

export function StatListWrapFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatListWrap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'list': !exists(json, 'List') ? undefined : ((json['List'] as Array<any>).map(StatFromJSON)),
    };
}

export function StatListWrapToJSON(value?: StatListWrap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'List': value.list === undefined ? undefined : ((value.list as Array<any>).map(StatToJSON)),
    };
}


