/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CidWithPath,
    CidWithPathFromJSON,
    CidWithPathFromJSONTyped,
    CidWithPathToJSON,
} from './';

/**
 * 
 * @export
 * @interface SupercontractExec
 */
export interface SupercontractExec {
    /**
     * [Cid](https://github.com/multiformats/cid) (version 1) - special content identifier.
     * @type {string}
     * @memberof SupercontractExec
     */
    scId?: string;
    /**
     * 
     * @type {CidWithPath}
     * @memberof SupercontractExec
     */
    txHash?: CidWithPath;
}

export function SupercontractExecFromJSON(json: any): SupercontractExec {
    return SupercontractExecFromJSONTyped(json, false);
}

export function SupercontractExecFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupercontractExec {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scId': !exists(json, 'ScId') ? undefined : json['ScId'],
        'txHash': !exists(json, 'TxHash') ? undefined : CidWithPathFromJSON(json['TxHash']),
    };
}

export function SupercontractExecToJSON(value?: SupercontractExec | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ScId': value.scId,
        'TxHash': CidWithPathToJSON(value.txHash),
    };
}


