/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Contract,
    ContractFromJSON,
    ContractFromJSONTyped,
    ContractToJSON,
} from './';

/**
 * 
 * @export
 * @interface SuperContract
 */
export interface SuperContract {
    /**
     * [Cid](https://github.com/multiformats/cid) (version 1) - special content identifier.
     * @type {string}
     * @memberof SuperContract
     */
    id?: string;
    /**
     * 
     * @type {Contract}
     * @memberof SuperContract
     */
    drive?: Contract;
    /**
     * [Cid](https://github.com/multiformats/cid) (version 1) - special content identifier.
     * @type {string}
     * @memberof SuperContract
     */
    file?: string;
    /**
     * 
     * @type {number}
     * @memberof SuperContract
     */
    vmversion?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof SuperContract
     */
    functions?: Array<string>;
}

export function SuperContractFromJSON(json: any): SuperContract {
    return SuperContractFromJSONTyped(json, false);
}

export function SuperContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuperContract {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'drive': !exists(json, 'drive') ? undefined : ContractFromJSON(json['drive']),
        'file': !exists(json, 'file') ? undefined : json['file'],
        'vmversion': !exists(json, 'vmversion') ? undefined : json['vmversion'],
        'functions': !exists(json, 'functions') ? undefined : json['functions'],
    };
}

export function SuperContractToJSON(value?: SuperContract | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'drive': ContractToJSON(value.drive),
        'file': value.file,
        'vmversion': value.vmversion,
        'functions': value.functions,
    };
}


