/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SuperContract,
    SuperContractFromJSON,
    SuperContractFromJSONTyped,
    SuperContractToJSON,
} from './';

/**
 * 
 * @export
 * @interface SuperContractWrap
 */
export interface SuperContractWrap {
    /**
     * 
     * @type {SuperContract}
     * @memberof SuperContractWrap
     */
    superContract?: SuperContract;
}

export function SuperContractWrapFromJSON(json: any): SuperContractWrap {
    return SuperContractWrapFromJSONTyped(json, false);
}

export function SuperContractWrapFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuperContractWrap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'superContract': !exists(json, 'SuperContract') ? undefined : SuperContractFromJSON(json['SuperContract']),
    };
}

export function SuperContractWrapToJSON(value?: SuperContractWrap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'SuperContract': SuperContractToJSON(value.superContract),
    };
}


