/* tslint:disable */
/* eslint-disable */
/**
 * DFMS API
 * DFMS node HTTP API. [Reference implementation in GO](https://github.com/proximax-storage/go-xpx-dfms-api-http) [API definition](https://github.com/proximax-storage/go-xpx-dfms-api)  API does not tries to follow idiomatic REST or other API patterns for reasons.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CidParam,
    CidParamFromJSON,
    CidParamFromJSONTyped,
    CidParamToJSON,
} from './';

/**
 *
 * @export
 * @interface VerifyResultDTO
 */
export interface VerifyResultDTO {
    /**
     * Hex encoded public keys.
     * @type {string}
     * @memberof VerifyResultDTO
     */
    replicator?: string;
    /**
     *
     * @type {Array<CidParam>}
     * @memberof VerifyResultDTO
     */
    faultyBlocks?: Array<CidParam>;
}

export function VerifyResultDTOFromJSON(json: any): VerifyResultDTO {
    return VerifyResultDTOFromJSONTyped(json, false);
}

export function VerifyResultDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyResultDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'replicator': !exists(json, 'replicator') ? undefined : json['replicator'],
        'faultyBlocks': !exists(json, 'faultyBlocks') ? undefined : ((json['faultyBlocks'] as Array<any>).map(CidParamFromJSON)),
    };
}

export function VerifyResultDTOToJSON(value?: VerifyResultDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'replicator': value.replicator,
        'faultyBlocks': value.faultyBlocks === undefined ? undefined : ((value.faultyBlocks as Array<any>).map(CidParamToJSON)),
    };
}


